### ISSUE TITLE
Roadmap 0.2.0

### ISSUE THREAD

**Issue by JakkuSakura** [qiujiangkun/kafcat#8]
The planned features includes:
- [ ] SSL connection
- [ ] Topic/Server metadata, at least show (like what [kaf](https://github.com/birdayz/kaf) does)
- [ ] Save servers to a config file(maybe interop with kaf config file)
- [ ] Benchmarking
- [ ] integrate deep with librdkafka(config, etc), while keeping the ability to swap the implementation.
Welcome more suggestions
